baseURL = "https://softwaretalks.ir/"
languageCode = "en-us"
title = "جلسات باز نرم‌افزاری "
theme="hugo-icon"
paginate = 100

# Metadata
[params]
  author = "SoftwareTalks"
  description = "دورهمی متخصصان و علاقمندان نرم‌افزار در مشهد از سال ۹۲"

#SoftwareTalks
[params.softwaretalks]
  nexteventdate="سه‌شنبه ۲۶ تیر ۹۷ ساعت ۱۹"
  nexteventsubject="Encapsulation به همراه علیرضا حسینی از بوشهر"
  nexteventlocation="‍<a href='https://www.youtube.com/softwaretalks'>کانال یوتیوب softwaretalks</a>"
  nexteventid="۸۵"
  eventcount="۸۴"
  speakercount="۴۵"
  topiccount="۸۱"
  scheduleddate="۲ مرداد ۹۷"

# Hero section (from here on is for icon theme)
[params.hero]
  img = "images/hero_bg.jpg"
  title = "جلسات باز نرم‌افزاری"  
  description = "دورهمی متخصصان و علاقمندان نرم‌افزار از سال ۹۲ "

# Navigation section
[params.nav]
  mission = "درباره"
  services = "اخبار"
  team = "‌"
  contact = "تماس با ما"
  # Include logo instead if HOME:
  # logo = "path/to/logo"

# Mission section
[params.mission]
  enable = true

  [params.mission.images]
    enable = true

    [[params.mission.images.list]]
      img = "images/3.png"
    [[params.mission.images.list]]
      img = "images/8.png"
    [[params.mission.images.list]]
      img = "images/6.jpg"
    [[params.mission.images.list]]
      img = "images/7.png"

  [[params.mission.item]]
    weight = 3
    name = "activities"
    title = "فعالیت‌ها"
    subtitle = "اگر تمایل به سخنرانی یا مشارکت در برگزاری جلسات باز نرم‌افزاری دارید با ما تماس بگیرید"
    description = "<p>علاوه بر برگزاری جلسات به صورت منظم، همراهان جلسات باز نرم‌افزاری فعالیت‌های دیگری را نیز تا کنون در جامعه نرم‌افزاری مشهد اجرا نموده‌اند</p><ul class='checked'><li>برگزاری دو دوره همایش یک روزه نرم‌افزاری  connect</li><li>برگزاری کارگاه‌های عملی با موضوعاتی نظیر git, python, telegram bots</li><li>برگزاری جشن پانصدهزارمین مقاله ویکی‌پدیا فارسی</li></ul>"

[[params.mission.item]]
    weight = 2
    name = "history"
    title = "تاریخچه"
    subtitle = "جلسات باز نرم‌افزاری یک دورهمی دوستانه برای متخصصان، علاقمندان، توسعه‌دهندگان، مدیران پروژه و فعالان صنعت نرم‌افزار است که هر دو هفته یک بار به صورت منظم برگزار می‌شود."
    description = "<p>جلسات باز نرم‌افزاری از سال ۹۲ در مشهد شروع شده است. در هر جلسه، پس از مرور اخبار و رویدادهای پیش رو، یک سخنرانی انجام می‌شود و در پایان جلسه نیز در صورتی که فرصت اجازه بدهد، بحث آزادی بین شرکت‌کنندگان شکل می‌گیرد. موضوع هر جلسه متفاوت است و توسط اعضا پیشنهاد می‌شود. اطلاع رسانی برگزاری جلسات باز نرم‌افزاری، از طریق وب سایت و شبکه‌های اجتماعی و خبرنامه ایمیلی و پیامکی انجام می‌شود.<p>"


  [[params.mission.item]]
    weight = 1
    name = "next"
    title = "جلسه بعدی"
    subtitle = ""
    description = "حضور در جلسات باز نرم‌افزاری برای عموم آزاد و رایگان است. <br> آدرس محل برگزاری روی نقشه، در [کانال تلگرام جلسات باز نرم‌افزاری مشهد](https://t.me/softwaretalks) آمده است.<br> "

  
# Services section
[params.services]
  enable = false
  video = false
  vidlink = ""
  title = ""
  description = ""

  [[params.services.item]]
    icon = ""
    title = ""
    description = ""

  [[params.services.item]]
    icon = ""
    title = ""
    description = ""

  [[params.services.item]]
    icon = "icon-paper-plane"
    title = "Light Speed"
    description = ""

  [[params.services.item]]
    icon = ""
    title = ""
    description = ""

  [[params.services.item]]
    icon = ""
    title = ""
    description = ""

  [[params.services.item]]
    icon = ""
    title = ""
    description = ""

# Work section
[params.work]
  enable = false

  [[params.work.item]]
    title = ""
    subtitle = ""
    img = ""

  [[params.work.item]]
    title = ""
    subtitle = ""
    img = ""

    [[params.work.item]]
    title = ""
    subtitle = ""
    img = ""

    [[params.work.item]]
    title = ""
    subtitle = ""
    img = ""

  [[params.work.item]]
    title = ""
    subtitle = ""
    img = ""

  [[params.work.item]]
    title = ""
    subtitle = ""
    img = ""

  [[params.work.item]]
    title = ""
    subtitle = ""
    img = ""

  [[params.work.item]]
    title = ""
    subtitle = ""
    img = ""

# Team section
[params.team]
  enable = false
  title = ""
  description = ""

  [[params.team.item]]
    name = ""
    position = ""
    description = ""
    img = ""
    facebook = "#"
    twitter = "#"
    dribbble = "#"
    instagram = "#"
    github = "#"

  [[params.team.item]]
    name = ""
    position = ""
    description = ""
    img = ""
    facebook = "#"
    twitter = "#"
    dribbble = "#"
    instagram = "#"
    github = "#"

  [[params.team.item]]
    name = ""
    position = ""
    description = ""
    img = ""
    facebook = "#"
    twitter = "#"
    dribbble = "#"
    instagram = "#"
    github = "#"


# Contact section
[params.contact]
  enable = true
  title = "تماس با ما"
  message = " این سایت به صورت اپن‌سورس در <a href='https://github.com/hameds/softwaretalks'>گیت‌هاب</a> در حال توسعه می‌باشد  <br> با ایمیل info@softwaretalks.ir در تماس باشید"

# Footer section
# Note here that the copyright and attribution statement must remain as part of the license agreement. If you wish to remove this, please contact freehtml5 and pay for a professional license.
[params.footer]
  enable = true
  note = "<p><small>&copy; 2016 Free HTML5 Template. All Rights Reserved. Designed by <a href='http://freehtml5.co/' target='_blank'>FreeHTML5.co</a> Hugo port by <a href='https://github.com/SteveLane/' target='_blank'>SteveLane</a> </small></p>"
  github = "https://github.com/hameds/softwaretalks"
  twitter = "https://twitter.com/softwaretalks"
  instagram = "https://instagram.com/softwaretalks"
  youtube = "https://www.youtube.com/softwaretalks"